[package]
name = "please"
version = "0.1.0"
authors = [ "Paweł Lewandowski <pl.lewandowski@proton.me>" ]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
